[package]
name = "ki-trainer-binaer"
version = "0.1.0"
edition = "2024"

[dependencies]
minifb = "0.28.0"
rand = "0.9"
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_arrays = "0.2.0"
serde_json = "1.0.151"

#cargo run --bin name
#tools
[[bin]]
name = "zeichner"
path = "tools/zeichner.rs"
[[bin]]
name = "sehen"
path = "tools/sehen.rs"
[[bin]]
name = "erweitern"
path = "tools/erweitern.rs"
[[bin]]
name = "livetester"
path = "tools/live_tester.rs"
[[bin]]
name = "bereinigen"
path = "tools/bereiniger.rs"
#main
[[bin]]
name = "main"
path = "src/main.rs"
